apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calendar-api
  labels:
    app.kubernetes.io/name: calendar-api
subjects:
  - kind: ServiceAccount
    name: calendar-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calendar-api
